#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: dev

#服务器配置
server:
  port: 80
#  servlet:
#    context-path: /sell


#微信
wechat:
  appId: wxfc15cac72c0b4e0e
  appsecret: cc8259a36e34308fb60796e129ed564e
  #获取 token 的 url
  tokenUrl: https://api.weixin.qq.com/cgi-bin/token
  #永久多媒体文件上传 url
  mediaUrl: http://file.api.weixin.qq.com/cgi-bin/media/upload?access_token=
